server:
  port: 8887
spring:
  redis:
    host: 47.106.135.182
    port: 6379
    password: liukai
    jedis:
      pool:
        max-active: 8
        max-wait: -1s
        min-idle: 0
        max-idle: 8
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://47.106.135.182:3306/oauth2?useUnicode=yes&characterEncoding=UTF-8
    username: root
    password: liukai
logging:
  level:
    org.springframework: info
owp:
  security:
    oauth2:
      storeType: jwt-key #或者jwt
      jwtSigningKey: owpSigningKey
      jwtSigningPublic: jwtSigningPublic
      serverUrl: http://127.0.0.1:8888/oauth
      clientId: user_one
      clientSecret: user_one_secret
      resourceId: demo